### PR TITLE
Add some useful methods for library and sample.

### PR DESCRIPTION
**Pull request by ysy950803**
Add OnItemClickListener and OnItemLongClickListener for ReclyclerView in the sample.
Add setExpandedText for SearchViewlayout.

### CODE REVIEW

**Comment by sahildave** [comment]
Can you bring up a use case for setExpandedText?

**Comment by ysy950803** [comment]
@sahildave For example, you are searching "Android" but you only input "An". And the search results list has shown "Android" on one item, so you can click the item then a full word can be set on the editText for searching.

**Comment by sahildave** [comment]
Ok. I am doing this myself in an app where in I findViewById and then set the text.
This seems a better API. 
Merging.

**Comment by ysy950803** [comment]
@sahildave Oh, Thanks for merging.

**Pull request merged**
