### PR TITLE
API for setting search icon

### PR DESCRIPTION
**Pull request by tim-bm**
Hi, sahildave. I added  a method which allows user to set the their own customized search icon. If there are any problems, plz let me know.

### CODE REVIEW

**Comment by sahildave** [comment]
@vguzzi `@DrawableRes` would be the correct annotation I believe.

**Comment by vguzzi** [comment]
@sahildave ah yes! Thank you

**Comment by EpsilonOrionis** [comment]
Hi, I'm the guy who requested the hint. How can I use implement these changes?

**Comment by tim-bm** [comment]
I have added two method for changing icons and tried to improve formatting.

**Comment by tim-bm** [comment]
@EpsilonOrionis  Hi, you can sync the fork to get the updates. To see this link for the instruction: https://help.github.com/articles/syncing-a-fork/

**Comment by sahildave** [comment]
Hey @tim-bm Can you add these changes to the PR. I would merge the pull request.

``` java
    /**
     * Allow user to set a search icon in the un-expanded view
     *
     * @param iconResource resource id of icon
     */
    public void setCollapsedIcon(@DrawableRes int iconResource) {
        ((ImageView) mSearchIcon).setImageResource(iconResource);
    }

    /**
     * Allow user to set a back icon in the expanded view
     *
     * @param iconResource resource id of icon
     */
    public void setExpandedBackIcon(@DrawableRes int iconResource) {
        ((ImageView) mBackButtonView).setImageResource(iconResource);
    }

    /**
     * Allow user to set a search icon in the expanded view
     *
     * @param iconResource resource id of icon
     */
    public void setExpandedSearchIcon(@DrawableRes int iconResource) {
        ((ImageView)mExpandedSearchIcon).setImageResource(iconResource);
    }

```

**Comment by tim-bm** [comment]
I have added the changes and sry for bad naming methods.

On Sunday, 22 November 2015, Sahil Dave notifications@github.com wrote:

> Hey @tim-bm https://github.com/tim-bm Can you add these changes to the
> PR. I would merge the pull request.
> 
> ```
> /**     * Allow user to set a search icon in the un-expanded view     *     * @param iconResource resource id of icon     */
> public void setCollapsedIcon(@DrawableRes int iconResource) {
>     ((ImageView) mSearchIcon).setImageResource(iconResource);
> }
> 
> /**     * Allow user to set a back icon in the expanded view     *     * @param iconResource resource id of icon     */
> public void setExpandedBackIcon(@DrawableRes int iconResource) {
>     ((ImageView) mBackButtonView).setImageResource(iconResource);
> }
> 
> /**     * Allow user to set a search icon in the expanded view     *     * @param iconResource resource id of icon     */
> public void setExpandedSearchIcon(@DrawableRes int iconResource) {
>     ((ImageView)mExpandedSearchIcon).setImageResource(iconResource);
> }
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sahildave/Search-View-Layout/pull/8#issuecomment-158740166
> .

## 

陈博添 Tim
Student Id:20112179
Software engineering international class, Department of software in NEU
tim_cbt@gmail.com
QQ:308496750

**Pull request merged**
